# Generated by Django 2.2.5 on 2021-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.CharField(blank=True, choices=[('ug', 'Undergraduate'), ('pgm', 'Postgraduate masters'), ('pgr', 'Postgraduate research')], default=None, max_length=20),
        ),
    ]
