# Generated by Django 2.2.5 on 2021-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0002_response_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='professional',
            field=models.CharField(blank=True, choices=[('low', '(0 - 2)'), ('moderate', '(3 - 5)'), ('high', '(5 - 10)'), ('advanced', '(above 10)')], default=None, max_length=20),
        ),
    ]
