# Generated by Django 2.2.5 on 2021-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_response_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='creative',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=20),
        ),
    ]
