# Generated by Django 2.2.5 on 2021-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0004_response_creative'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='creativity_example',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
