# Generated by Django 2.2.5 on 2021-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0005_response_creativity_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='hand',
            field=models.CharField(choices=[('right', 'Right hand'), ('left', 'Left hand'), ('both', 'Both hands')], default=None, max_length=11),
        ),
    ]
