# Generated by Django 2.2.5 on 2021-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0006_response_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='trial_signup',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
